# Generated by Django 5.1.5 on 2025-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_is_featured_article_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
