# Generated by Django 5.1.5 on 2025-04-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_meta_description_article_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("POLITIK", "Politik"),
                    ("SOSIAL", "Sosial"),
                    ("PERTEMUAN", "Pertemuan"),
                ],
                max_length=20,
            ),
        ),
    ]
